import mongoose from "mongoose";
import dotenv from "dotenv";
import { connectDB } from "../config/db";
import { Question } from "../models/Question";
import { Achievement } from "../models/Achievement";

dotenv.config();

type SeedCategory =
  | "JavaScript"
  | "React"
  | "TypeScript"
  | "CSS"
  | "HTML"
  | "DSA"
  | "DBMS"
  | "Computer Networks"
  | "Operating Systems"
  | "HR";

type SeedDifficulty = "Beginner" | "Intermediate" | "Advanced";

interface SeedQuestion {
  question: string;
  category: SeedCategory;
  topic: string;
  difficulty: SeedDifficulty;
  type: "MCQ";
  options: string[];
  correctAnswer: string;
  explanation: string;
  tags: string[];
}

const shuffleArray = <T>(array: T[]): T[] => {
  const arr = [...array];
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr;
};

const jsQuestions: SeedQuestion[] = [
  { question: "Which of the following is a JavaScript primitive type?", category: "JavaScript", topic: "Types", difficulty: "Beginner", type: "MCQ", options: ["string", "Array", "Object", "Function"], correctAnswer: "string", explanation: "string is a primitive; Array, Object, and Function are all objects.", tags: ["types", "primitives"] },
  { question: "What does `typeof null` evaluate to?", category: "JavaScript", topic: "Types", difficulty: "Beginner", type: "MCQ", options: ["'null'", "'undefined'", "'object'", "'number'"], correctAnswer: "'object'", explanation: "Due to a long-standing bug, typeof null returns 'object' in JavaScript.", tags: ["types", "quirks"] },
  { question: "Which array method returns a new array by applying a function to every element?", category: "JavaScript", topic: "Arrays", difficulty: "Beginner", type: "MCQ", options: ["forEach", "map", "filter", "reduce"], correctAnswer: "map", explanation: "map transforms each element and returns a new array of the same length.", tags: ["arrays", "methods"] },
  { question: "What does the expression `2 + '2'` evaluate to?", category: "JavaScript", topic: "Operators", difficulty: "Beginner", type: "MCQ", options: ["4", "'22'", "NaN", "TypeError"], correctAnswer: "'22'", explanation: "The + operator coerces the number to a string and concatenates them.", tags: ["operators", "coercion"] },
  { question: "Which keyword declares a block-scoped variable that can be reassigned?", category: "JavaScript", topic: "ES6", difficulty: "Beginner", type: "MCQ", options: ["var", "let", "const", "function"], correctAnswer: "let", explanation: "let is block-scoped and reassignable; const is block-scoped but immutable.", tags: ["es6", "scope"] },
  { question: "What does the spread operator (...) do?", category: "JavaScript", topic: "ES6", difficulty: "Beginner", type: "MCQ", options: ["Copies an iterable into individual elements", "Creates a new Promise", "Terminates a loop", "Declares a constant"], correctAnswer: "Copies an iterable into individual elements", explanation: "Spread expands arrays, objects, or other iterables into their individual elements.", tags: ["es6", "syntax"] },
  { question: "Which of these is NOT a JavaScript primitive type?", category: "JavaScript", topic: "Types", difficulty: "Beginner", type: "MCQ", options: ["Symbol", "BigInt", "Float", "undefined"], correctAnswer: "Float", explanation: "JavaScript has Number, not separate Float or Integer primitive types.", tags: ["types", "primitives"] },
  { question: "What is a closure in JavaScript?", category: "JavaScript", topic: "Closures", difficulty: "Intermediate", type: "MCQ", options: ["A function that retains access to its outer scope", "A way to close the browser tab", "A loop that never terminates", "A type of runtime error"], correctAnswer: "A function that retains access to its outer scope", explanation: "Closures let inner functions access outer function variables even after it returns.", tags: ["scope", "functions"] },
  { question: "Which method removes the last element from an array and returns it?", category: "JavaScript", topic: "Arrays", difficulty: "Beginner", type: "MCQ", options: ["shift()", "pop()", "splice()", "slice()"], correctAnswer: "pop()", explanation: "pop() removes the last element; shift() removes the first element.", tags: ["arrays", "methods"] },
  { question: "What does NaN stand for?", category: "JavaScript", topic: "Types", difficulty: "Beginner", type: "MCQ", options: ["Not a Null", "Not a Number", "New and Null", "None and Null"], correctAnswer: "Not a Number", explanation: "NaN represents a computational error where a number was expected.", tags: ["types", "numbers"] },
  { question: "Which function syntax has a lexical `this` binding?", category: "JavaScript", topic: "Functions", difficulty: "Intermediate", type: "MCQ", options: ["function declaration", "arrow function", "method shorthand", "generator function"], correctAnswer: "arrow function", explanation: "Arrow functions inherit `this` from the enclosing scope rather than having their own.", tags: ["functions", "es6"] },
  { question: "What is hoisting in JavaScript?", category: "JavaScript", topic: "Hoisting", difficulty: "Intermediate", type: "MCQ", options: ["Moving declarations to the top of their scope", "Deleting unused variables", "Compiling code ahead of time", "Caching function results"], correctAnswer: "Moving declarations to the top of their scope", explanation: "Function and variable declarations are hoisted; let/const remain in the temporal dead zone.", tags: ["scope", "hoisting"] },
  { question: "Which operator checks value AND type equality without coercion?", category: "JavaScript", topic: "Operators", difficulty: "Beginner", type: "MCQ", options: ["==", "===", "=", "=>"], correctAnswer: "===", explanation: "=== is strict equality; == performs type coercion before comparing.", tags: ["operators", "comparison"] },
  { question: "What is the result of `Boolean([])`?", category: "JavaScript", topic: "Types", difficulty: "Beginner", type: "MCQ", options: ["false", "true", "undefined", "0"], correctAnswer: "true", explanation: "An empty array is an object, and objects are truthy in JavaScript.", tags: ["types", "truthiness"] },
  { question: "Which method adds one or more elements to the end of an array?", category: "JavaScript", topic: "Arrays", difficulty: "Beginner", type: "MCQ", options: ["push()", "unshift()", "concat()", "append()"], correctAnswer: "push()", explanation: "push() appends to the end; unshift() prepends to the beginning.", tags: ["arrays", "methods"] },
  { question: "What does `Object.freeze()` do?", category: "JavaScript", topic: "Objects", difficulty: "Intermediate", type: "MCQ", options: ["Prevents all changes to an object", "Makes an object iterable", "Converts it to JSON", "Creates a deep clone"], correctAnswer: "Prevents all changes to an object", explanation: "Object.freeze prevents adding, removing, or changing properties of the target.", tags: ["objects", "immutability"] },
  { question: "What is the purpose of `Promise.all`?", category: "JavaScript", topic: "Async", difficulty: "Intermediate", type: "MCQ", options: ["Waits for all promises to resolve", "Returns the fastest settled promise", "Rejects if any resolves", "Cancels pending promises"], correctAnswer: "Waits for all promises to resolve", explanation: "Promise.all resolves when every input promise resolves and rejects if any rejects.", tags: ["async", "promises"] },
  { question: "Which statement about `let` and `const` is true?", category: "JavaScript", topic: "Variables", difficulty: "Beginner", type: "MCQ", options: ["Both are block-scoped", "var is block-scoped", "const can be reassigned", "let cannot be used in loops"], correctAnswer: "Both are block-scoped", explanation: "let and const are block-scoped; var is function-scoped.", tags: ["variables", "scope"] },
  { question: "What does the optional chaining operator `?.` do?", category: "JavaScript", topic: "ES2020", difficulty: "Beginner", type: "MCQ", options: ["Safely accesses nested properties without errors", "Declares an optional variable", "Chains multiple promises", "Merges two objects"], correctAnswer: "Safely accesses nested properties without errors", explanation: "?. short-circuits to undefined if any part of the chain is null or undefined.", tags: ["es2020", "syntax"] },
  { question: "What is the event loop responsible for in JavaScript?", category: "JavaScript", topic: "Event Loop", difficulty: "Intermediate", type: "MCQ", options: ["Handling async callbacks via a task queue", "Compiling JavaScript code", "Managing CSS animations", "Rendering the DOM tree"], correctAnswer: "Handling async callbacks via a task queue", explanation: "The event loop pulls callbacks from queues and runs them when the call stack is empty.", tags: ["async", "runtime"] },
  { question: "What is a generator function?", category: "JavaScript", topic: "Functions", difficulty: "Advanced", type: "MCQ", options: ["A function that can pause and resume execution", "A function that runs in parallel threads", "A constructor for objects", "A recursive helper"], correctAnswer: "A function that can pause and resume execution", explanation: "Declared with function* and using yield, generators can suspend and resume.", tags: ["functions", "es6"] },
  { question: "Which method creates a shallow copy of an object?", category: "JavaScript", topic: "Objects", difficulty: "Intermediate", type: "MCQ", options: ["Object.assign()", "Object.freeze()", "Object.seal()", "Object.create()"], correctAnswer: "Object.assign()", explanation: "Object.assign copies own enumerable properties into a target; nested objects are shared.", tags: ["objects", "copying"] },
];

const reactQuestions: SeedQuestion[] = [
  { question: "Which hook is used to manage local component state?", category: "React", topic: "Hooks", difficulty: "Beginner", type: "MCQ", options: ["useState", "useEffect", "useContext", "useRef"], correctAnswer: "useState", explanation: "useState returns the current state value and a setter function.", tags: ["hooks", "state"] },
  { question: "What is JSX?", category: "React", topic: "JSX", difficulty: "Beginner", type: "MCQ", options: ["JavaScript XML syntax extension", "A standalone templating language", "A CSS preprocessor", "A database query language"], correctAnswer: "JavaScript XML syntax extension", explanation: "JSX lets you write HTML-like syntax that Babel compiles to React.createElement calls.", tags: ["jsx", "syntax"] },
  { question: "Which hook is used to perform side effects in a component?", category: "React", topic: "Hooks", difficulty: "Beginner", type: "MCQ", options: ["useState", "useEffect", "useMemo", "useCallback"], correctAnswer: "useEffect", explanation: "useEffect runs after render for data fetching, subscriptions, and DOM updates.", tags: ["hooks", "effects"] },
  { question: "What is the Virtual DOM?", category: "React", topic: "Virtual DOM", difficulty: "Beginner", type: "MCQ", options: ["An in-memory representation of the real DOM", "A browser built-in API", "A CSS rendering engine", "A server-side database"], correctAnswer: "An in-memory representation of the real DOM", explanation: "React diffs the virtual DOM against the real DOM to minimize costly updates.", tags: ["virtual-dom", "rendering"] },
  { question: "What is the purpose of keys in React lists?", category: "React", topic: "Lists", difficulty: "Beginner", type: "MCQ", options: ["Identifying which items changed for efficient updates", "Styling list items", "Sorting the array", "Encrypting the data"], correctAnswer: "Identifying which items changed for efficient updates", explanation: "Stable keys help React reconcile list items correctly during re-renders.", tags: ["lists", "rendering"] },
  { question: "Which hook memoizes the result of an expensive calculation?", category: "React", topic: "Performance", difficulty: "Intermediate", type: "MCQ", options: ["useMemo", "useState", "useRef", "useContext"], correctAnswer: "useMemo", explanation: "useMemo recomputes only when its listed dependencies change.", tags: ["hooks", "performance"] },
  { question: "Which hook is used to consume a Context value?", category: "React", topic: "Context", difficulty: "Intermediate", type: "MCQ", options: ["useContext", "useState", "useEffect", "useReducer"], correctAnswer: "useContext", explanation: "useContext reads the nearest provider value for that context.", tags: ["hooks", "context"] },
  { question: "What does the dependency array of `useEffect` control?", category: "React", topic: "Hooks", difficulty: "Intermediate", type: "MCQ", options: ["When the effect should re-run", "The component styling", "State initialization", "Data encryption"], correctAnswer: "When the effect should re-run", explanation: "An empty array runs once; dependencies make the effect re-run on change.", tags: ["hooks", "effects"] },
  { question: "What is the purpose of `React.memo`?", category: "React", topic: "Performance", difficulty: "Intermediate", type: "MCQ", options: ["Prevents unnecessary re-renders of functional components", "Memoizes state values", "Creates DOM references", "Handles form submission"], correctAnswer: "Prevents unnecessary re-renders of functional components", explanation: "React.memo skips re-rendering when props are shallowly equal.", tags: ["performance", "components"] },
  { question: "What is a controlled component?", category: "React", topic: "Forms", difficulty: "Beginner", type: "MCQ", options: ["A form element whose value is driven by React state", "A component with no state", "A server-rendered component", "A component that never re-renders"], correctAnswer: "A form element whose value is driven by React state", explanation: "In controlled components React is the single source of truth for input values.", tags: ["forms", "state"] },
  { question: "Which method is used to create a React element?", category: "React", topic: "Core", difficulty: "Intermediate", type: "MCQ", options: ["React.createElement", "document.createElement", "React.makeElement", "React.newElement"], correctAnswer: "React.createElement", explanation: "JSX compiles down to React.createElement calls.", tags: ["core", "jsx"] },
  { question: "What does the `useRef` hook return?", category: "React", topic: "Refs", difficulty: "Beginner", type: "MCQ", options: ["A mutable ref object", "A new state variable", "A callback function", "The DOM node directly"], correctAnswer: "A mutable ref object", explanation: "useRef returns an object whose .current persists across renders without re-rendering.", tags: ["refs", "hooks"] },
  { question: "What is prop drilling?", category: "React", topic: "Props", difficulty: "Intermediate", type: "MCQ", options: ["Passing props through many nested components", "Drilling holes into components", "A type of CSS animation", "A testing technique"], correctAnswer: "Passing props through many nested components", explanation: "Prop drilling passes data down manually through intermediate components; Context can avoid it.", tags: ["props", "patterns"] },
  { question: "Which React feature enables code splitting?", category: "React", topic: "Performance", difficulty: "Advanced", type: "MCQ", options: ["React.lazy", "React.memo", "useState", "useRef"], correctAnswer: "React.lazy", explanation: "React.lazy dynamically imports a component so it loads only when needed.", tags: ["performance", "loading"] },
  { question: "What does the `useReducer` hook manage?", category: "React", topic: "State", difficulty: "Intermediate", type: "MCQ", options: ["Complex state via a reducer function", "CSS styles", "DOM references", "Network requests"], correctAnswer: "Complex state via a reducer function", explanation: "useReducer is ideal when state transitions depend on previous state and actions.", tags: ["state", "hooks"] },
  { question: "What is the Context API used for?", category: "React", topic: "Context", difficulty: "Intermediate", type: "MCQ", options: ["Sharing data across the tree without prop drilling", "Creating animations", "Defining routes", "Writing tests"], correctAnswer: "Sharing data across the tree without prop drilling", explanation: "Context provides values to deeply nested components without manual prop passing.", tags: ["context", "state"] },
  { question: "Which hook runs synchronously immediately after DOM mutations?", category: "React", topic: "Hooks", difficulty: "Advanced", type: "MCQ", options: ["useLayoutEffect", "useEffect", "useCallback", "useMemo"], correctAnswer: "useLayoutEffect", explanation: "useLayoutEffect runs before the browser paints, so it can read layout and apply changes.", tags: ["hooks", "effects"] },
  { question: "What is a React portal?", category: "React", topic: "Rendering", difficulty: "Advanced", type: "MCQ", options: ["A way to render children outside the parent DOM hierarchy", "A client-side router", "A state management library", "A CSS module system"], correctAnswer: "A way to render children outside the parent DOM hierarchy", explanation: "Portals let modals and tooltips escape overflow while keeping React's event model.", tags: ["rendering", "dom"] },
  { question: "What is the main difference between state and props?", category: "React", topic: "State", difficulty: "Beginner", type: "MCQ", options: ["State is internal and mutable; props are external and read-only", "State is external; props are internal", "They are exactly the same", "Props are mutable; state is fixed"], correctAnswer: "State is internal and mutable; props are external and read-only", explanation: "Components own and change their state; props are passed in and are read-only.", tags: ["state", "props"] },
  { question: "Which hook prevents unnecessary re-creation of callback functions?", category: "React", topic: "Performance", difficulty: "Intermediate", type: "MCQ", options: ["useCallback", "useState", "useEffect", "useRef"], correctAnswer: "useCallback", explanation: "useCallback returns a memoized version of the callback that only changes when deps change.", tags: ["performance", "hooks"] },
];

const tsQuestions: SeedQuestion[] = [
  { question: "What is TypeScript?", category: "TypeScript", topic: "Basics", difficulty: "Beginner", type: "MCQ", options: ["JavaScript with static typing", "A relational database", "A CSS preprocessor", "A backend server"], correctAnswer: "JavaScript with static typing", explanation: "TypeScript is a typed superset of JavaScript that compiles to plain JS.", tags: ["types", "basics"] },
  { question: "Which keyword defines a contract for an object's shape?", category: "TypeScript", topic: "Interfaces", difficulty: "Beginner", type: "MCQ", options: ["interface", "class", "enum", "module"], correctAnswer: "interface", explanation: "Interfaces describe the structure that an object must satisfy.", tags: ["interfaces", "types"] },
  { question: "What is a union type?", category: "TypeScript", topic: "Types", difficulty: "Beginner", type: "MCQ", options: ["A type that can be one of several types", "A loop construct", "A database table", "A CSS selector"], correctAnswer: "A type that can be one of several types", explanation: "Union types combine multiple types with the | operator.", tags: ["types", "union"] },
  { question: "What does the `any` type do?", category: "TypeScript", topic: "Types", difficulty: "Beginner", type: "MCQ", options: ["Disables type checking for a value", "Creates a new primitive", "Declares a constant", "Imports a module"], correctAnswer: "Disables type checking for a value", explanation: "any opts out of type safety and should generally be avoided.", tags: ["types", "any"] },
  { question: "What are generics used for?", category: "TypeScript", topic: "Generics", difficulty: "Intermediate", type: "MCQ", options: ["Creating reusable components that work with multiple types", "Styling components", "Defining routes", "Writing tests"], correctAnswer: "Creating reusable components that work with multiple types", explanation: "Generics let functions, classes, and interfaces accept type parameters.", tags: ["generics", "reuse"] },
  { question: "What is an enum in TypeScript?", category: "TypeScript", topic: "Enums", difficulty: "Intermediate", type: "MCQ", options: ["A set of named constants", "A type of loop", "A utility function", "A CSS class"], correctAnswer: "A set of named constants", explanation: "Enums define a collection of related, named constant values.", tags: ["enums", "constants"] },
  { question: "What does the `as` keyword perform?", category: "TypeScript", topic: "Assertions", difficulty: "Intermediate", type: "MCQ", options: ["A type assertion", "A variable declaration", "A module import", "A class definition"], correctAnswer: "A type assertion", explanation: "Type assertions tell the compiler to treat a value as a specific type.", tags: ["assertions", "types"] },
  { question: "What is type inference?", category: "TypeScript", topic: "Types", difficulty: "Beginner", type: "MCQ", options: ["The compiler deduces types automatically", "You must annotate every variable", "It removes all types", "It converts types to strings"], correctAnswer: "The compiler deduces types automatically", explanation: "TypeScript infers types from initial values and usage when not annotated.", tags: ["types", "inference"] },
  { question: "Which utility type makes all properties optional?", category: "TypeScript", topic: "Utility Types", difficulty: "Intermediate", type: "MCQ", options: ["Partial", "Pick", "Omit", "Readonly"], correctAnswer: "Partial", explanation: "Partial<T> sets every property of T to optional.", tags: ["utility-types", "types"] },
  { question: "What is a tuple?", category: "TypeScript", topic: "Types", difficulty: "Intermediate", type: "MCQ", options: ["A fixed-size array with typed positions", "A type of loop", "A database row", "A CSS layout"], correctAnswer: "A fixed-size array with typed positions", explanation: "Tuples represent arrays with a known number and types of elements.", tags: ["types", "tuples"] },
  { question: "What are access modifiers in TypeScript classes?", category: "TypeScript", topic: "Classes", difficulty: "Intermediate", type: "MCQ", options: ["public, private, protected", "let, const, var", "if, else, for", "type, interface, enum"], correctAnswer: "public, private, protected", explanation: "Access modifiers control the visibility of class members.", tags: ["classes", "oop"] },
  { question: "What does the `readonly` modifier do?", category: "TypeScript", topic: "Modifiers", difficulty: "Intermediate", type: "MCQ", options: ["Prevents reassignment after initialization", "Makes a property public", "Declares a constant function", "Imports a module"], correctAnswer: "Prevents reassignment after initialization", explanation: "readonly properties can be set once and then cannot be changed.", tags: ["modifiers", "types"] },
  { question: "What is the `unknown` type?", category: "TypeScript", topic: "Types", difficulty: "Advanced", type: "MCQ", options: ["A type-safe counterpart to any", "A keyword for loops", "A CSS property", "A database type"], correctAnswer: "A type-safe counterpart to any", explanation: "unknown forces you to narrow the type before using the value, unlike any.", tags: ["types", "safety"] },
  { question: "What does the `satisfies` operator do?", category: "TypeScript", topic: "Advanced", difficulty: "Advanced", type: "MCQ", options: ["Checks a value matches a type without widening its inferred type", "Assigns a new value", "Declares a variable", "Imports a module"], correctAnswer: "Checks a value matches a type without widening its inferred type", explanation: "satisfies validates type compatibility while preserving literal inference.", tags: ["advanced", "types"] },
];

const cssQuestions: SeedQuestion[] = [
  { question: "What does CSS stand for?", category: "CSS", topic: "Basics", difficulty: "Beginner", type: "MCQ", options: ["Cascading Style Sheets", "Creative Style Sheets", "Computer Style Sheets", "Colorful Style Sheets"], correctAnswer: "Cascading Style Sheets", explanation: "CSS describes how HTML elements are presented and styled.", tags: ["basics", "css"] },
  { question: "Which property sets the text color of an element?", category: "CSS", topic: "Text", difficulty: "Beginner", type: "MCQ", options: ["color", "text-color", "font-color", "background-color"], correctAnswer: "color", explanation: "The color property sets the foreground (text) color.", tags: ["text", "properties"] },
  { question: "What is the default display value of a `<div>` element?", category: "CSS", topic: "Layout", difficulty: "Beginner", type: "MCQ", options: ["block", "inline", "flex", "grid"], correctAnswer: "block", explanation: "div elements are block-level by default and span the full available width.", tags: ["layout", "display"] },
  { question: "Which unit is relative to the root element's font size?", category: "CSS", topic: "Units", difficulty: "Intermediate", type: "MCQ", options: ["rem", "em", "px", "vh"], correctAnswer: "rem", explanation: "rem is relative to the root (html) font size; em is relative to the parent.", tags: ["units", "layout"] },
  { question: "What does the `z-index` property control?", category: "CSS", topic: "Positioning", difficulty: "Beginner", type: "MCQ", options: ["Stacking order of overlapping elements", "Font size", "Opacity level", "Text alignment"], correctAnswer: "Stacking order of overlapping elements", explanation: "z-index controls paint order among positioned elements in a stacking context.", tags: ["positioning", "layout"] },
  { question: "Which selector has the highest specificity?", category: "CSS", topic: "Selectors", difficulty: "Intermediate", type: "MCQ", options: ["#id", "element", ".class", "*"], correctAnswer: "#id", explanation: "ID selectors have higher specificity than class, element, and universal selectors.", tags: ["selectors", "cascade"] },
  { question: "What is Flexbox primarily used for?", category: "CSS", topic: "Flexbox", difficulty: "Beginner", type: "MCQ", options: ["One-dimensional layout and alignment", "3D graphics", "Database queries", "Encryption"], correctAnswer: "One-dimensional layout and alignment", explanation: "Flexbox lays out items in a single row or column with flexible spacing.", tags: ["flexbox", "layout"] },
  { question: "Which property creates space inside an element, between its content and border?", category: "CSS", topic: "Box Model", difficulty: "Beginner", type: "MCQ", options: ["padding", "margin", "border", "outline"], correctAnswer: "padding", explanation: "padding is the inner spacing; margin is the outer spacing.", tags: ["box-model", "layout"] },
  { question: "What does `position: absolute` do?", category: "CSS", topic: "Positioning", difficulty: "Intermediate", type: "MCQ", options: ["Positions relative to the nearest positioned ancestor", "Positions relative to the viewport only", "Keeps the element in normal flow", "Centers the element automatically"], correctAnswer: "Positions relative to the nearest positioned ancestor", explanation: "absolute takes the element out of flow and anchors it to a positioned ancestor.", tags: ["positioning", "layout"] },
  { question: "Which CSS feature allows reusable values via custom properties?", category: "CSS", topic: "Variables", difficulty: "Beginner", type: "MCQ", options: ["CSS variables", "Media queries", "Pseudo-classes", "Transforms"], correctAnswer: "CSS variables", explanation: "Custom properties (--name) enable reusable, themeable values.", tags: ["variables", "css"] },
  { question: "What does `box-sizing: border-box` do?", category: "CSS", topic: "Box Model", difficulty: "Intermediate", type: "MCQ", options: ["Includes padding and border in the element's width", "Excludes padding from the width", "Centers the content", "Hides overflow"], correctAnswer: "Includes padding and border in the element's width", explanation: "border-box makes width include content, padding, and border.", tags: ["box-model", "layout"] },
  { question: "Which property animates changes smoothly between values over time?", category: "CSS", topic: "Animation", difficulty: "Beginner", type: "MCQ", options: ["transition", "transform", "display", "visibility"], correctAnswer: "transition", explanation: "transition animates a property change; transform applies a visual change.", tags: ["animation", "css"] },
];

const htmlQuestions: SeedQuestion[] = [
  { question: "Which tag defines the largest heading?", category: "HTML", topic: "Basics", difficulty: "Beginner", type: "MCQ", options: ["<h1>", "<head>", "<heading>", "<h6>"], correctAnswer: "<h1>", explanation: "Headings range from <h1> (largest) to <h6> (smallest).", tags: ["html", "semantics"] },
  { question: "Which attribute provides alternative text for an image?", category: "HTML", topic: "Attributes", difficulty: "Beginner", type: "MCQ", options: ["alt", "src", "title", "href"], correctAnswer: "alt", explanation: "alt text is used by screen readers and shown if the image fails to load.", tags: ["html", "accessibility"] },
  { question: "What does the `lang` attribute declare?", category: "HTML", topic: "Accessibility", difficulty: "Beginner", type: "MCQ", options: ["The language of the page content", "The page title", "A linked stylesheet", "Metadata keywords"], correctAnswer: "The language of the page content", explanation: "lang helps assistive tech and search engines determine the content language.", tags: ["html", "a11y"] },
  { question: "Which element is semantic for primary navigation links?", category: "HTML", topic: "Semantics", difficulty: "Intermediate", type: "MCQ", options: ["<nav>", "<div>", "<span>", "<section>"], correctAnswer: "<nav>", explanation: "nav is intended for major navigation blocks within a page.", tags: ["html", "semantics"] },
  { question: "What is the purpose of the viewport meta tag?", category: "HTML", topic: "Meta", difficulty: "Beginner", type: "MCQ", options: ["Controls layout on mobile devices", "Loads an external CSS file", "Defines the document title", "Creates a form"], correctAnswer: "Controls layout on mobile devices", explanation: "The viewport meta tag sets how the page scales on different screen sizes.", tags: ["html", "responsive"] },
  { question: "Which element embeds executable JavaScript?", category: "HTML", topic: "Scripting", difficulty: "Beginner", type: "MCQ", options: ["<script>", "<js>", "<code>", "<style>"], correctAnswer: "<script>", explanation: "script elements contain or reference JavaScript code.", tags: ["html", "scripting"] },
  { question: "Which attribute makes a form input mandatory?", category: "HTML", topic: "Forms", difficulty: "Beginner", type: "MCQ", options: ["required", "mandatory", "validate", "need"], correctAnswer: "required", explanation: "The required attribute enforces that the field must be filled before submit.", tags: ["html", "forms"] },
  { question: "What is the difference between `<strong>` and `<b>`?", category: "HTML", topic: "Semantics", difficulty: "Beginner", type: "MCQ", options: ["<strong> conveys semantic importance; <b> is purely visual", "They are identical", "<b> conveys importance", "<strong> is purely visual"], correctAnswer: "<strong> conveys semantic importance; <b> is purely visual", explanation: "strong has meaning; b only changes appearance.", tags: ["html", "semantics"] },
  { question: "Which element represents self-contained, independently distributable content?", category: "HTML", topic: "Semantics", difficulty: "Intermediate", type: "MCQ", options: ["<article>", "<section>", "<div>", "<span>"], correctAnswer: "<article>", explanation: "article is for content that makes sense on its own, like a blog post.", tags: ["html", "semantics"] },
  { question: "What does the `href` attribute specify on an anchor?", category: "HTML", topic: "Attributes", difficulty: "Beginner", type: "MCQ", options: ["The URL the link points to", "Alternative text", "The image source", "A CSS class name"], correctAnswer: "The URL the link points to", explanation: "href defines the destination of a hyperlink.", tags: ["html", "attributes"] },
  { question: "Which element defines an unordered (bulleted) list?", category: "HTML", topic: "Lists", difficulty: "Beginner", type: "MCQ", options: ["<ul>", "<ol>", "<li>", "<list>"], correctAnswer: "<ul>", explanation: "ul is unordered; ol is ordered; li are the list items.", tags: ["html", "lists"] },
  { question: "What does a `<label>` element do?", category: "HTML", topic: "Forms", difficulty: "Beginner", type: "MCQ", options: ["Associates text with a form control", "Creates a page heading", "Loads an image", "Defines a table"], correctAnswer: "Associates text with a form control", explanation: "label improves accessibility and click targets for inputs.", tags: ["html", "forms"] },
];

const dsaQuestions: SeedQuestion[] = [
  { question: "What is the time complexity of binary search on a sorted array?", category: "DSA", topic: "Searching", difficulty: "Beginner", type: "MCQ", options: ["O(log n)", "O(n)", "O(n^2)", "O(1)"], correctAnswer: "O(log n)", explanation: "Binary search halves the search space in each step.", tags: ["searching", "complexity"] },
  { question: "Which data structure follows FIFO (First In, First Out) ordering?", category: "DSA", topic: "Data Structures", difficulty: "Beginner", type: "MCQ", options: ["Queue", "Stack", "Tree", "Graph"], correctAnswer: "Queue", explanation: "Queues remove the oldest inserted element first; stacks use LIFO.", tags: ["data-structures", "queues"] },
  { question: "Which data structure follows LIFO (Last In, First Out) ordering?", category: "DSA", topic: "Data Structures", difficulty: "Beginner", type: "MCQ", options: ["Stack", "Queue", "Array", "Heap"], correctAnswer: "Stack", explanation: "Stacks remove the most recently added element first.", tags: ["data-structures", "stacks"] },
  { question: "What is the worst-case time complexity of QuickSort?", category: "DSA", topic: "Sorting", difficulty: "Intermediate", type: "MCQ", options: ["O(n^2)", "O(n log n)", "O(n)", "O(log n)"], correctAnswer: "O(n^2)", explanation: "Worst case happens when the pivot is always the smallest or largest element.", tags: ["sorting", "complexity"] },
  { question: "Which algorithm finds the shortest paths from a source in a weighted graph?", category: "DSA", topic: "Graphs", difficulty: "Advanced", type: "MCQ", options: ["Dijkstra's algorithm", "Binary search", "Merge sort", "Depth-first search"], correctAnswer: "Dijkstra's algorithm", explanation: "Dijkstra computes shortest paths with non-negative edge weights.", tags: ["graphs", "shortest-path"] },
  { question: "Which of these sorting algorithms is stable?", category: "DSA", topic: "Sorting", difficulty: "Intermediate", type: "MCQ", options: ["Merge Sort", "Quick Sort", "Heap Sort", "Selection Sort"], correctAnswer: "Merge Sort", explanation: "Merge sort preserves the relative order of equal elements.", tags: ["sorting", "stability"] },
  { question: "What is the average time complexity for lookup in a hash map?", category: "DSA", topic: "Hashing", difficulty: "Intermediate", type: "MCQ", options: ["O(1)", "O(n)", "O(log n)", "O(n^2)"], correctAnswer: "O(1)", explanation: "With a good hash function, average access is constant time.", tags: ["hashing", "complexity"] },
  { question: "Which data structure is used to implement recursion?", category: "DSA", topic: "Data Structures", difficulty: "Intermediate", type: "MCQ", options: ["Stack", "Queue", "Linked List", "Graph"], correctAnswer: "Stack", explanation: "The call stack stores activation records for recursive function calls.", tags: ["data-structures", "recursion"] },
  { question: "What is a binary tree?", category: "DSA", topic: "Trees", difficulty: "Intermediate", type: "MCQ", options: ["A tree where each node has at most two children", "A tree where every node has exactly two children", "A linear list", "A graph with cycles"], correctAnswer: "A tree where each node has at most two children", explanation: "Binary trees restrict each node to zero, one, or two children.", tags: ["trees", "data-structures"] },
  { question: "What does dynamic programming do?", category: "DSA", topic: "DP", difficulty: "Advanced", type: "MCQ", options: ["Solves problems by combining solutions to overlapping subproblems", "Sorts arrays in place", "Encrypts data", "Builds binary trees"], correctAnswer: "Solves problems by combining solutions to overlapping subproblems", explanation: "DP stores subproblem results to avoid redundant computation.", tags: ["dp", "optimization"] },
  { question: "Which tree traversal visits the root between the left and right subtrees?", category: "DSA", topic: "Trees", difficulty: "Intermediate", type: "MCQ", options: ["In-order", "Pre-order", "Post-order", "Level-order"], correctAnswer: "In-order", explanation: "In-order: left subtree, node, right subtree (gives sorted order for BSTs).", tags: ["trees", "traversal"] },
  { question: "What is a min-heap?", category: "DSA", topic: "Heaps", difficulty: "Intermediate", type: "MCQ", options: ["A complete binary tree with the smallest element at the root", "A sorted array", "A linked list of minimum values", "A graph with no cycles"], correctAnswer: "A complete binary tree with the smallest element at the root", explanation: "In a min-heap every parent node is less than or equal to its children.", tags: ["heaps", "trees"] },
  { question: "What does the sliding window technique optimize?", category: "DSA", topic: "Arrays", difficulty: "Intermediate", type: "MCQ", options: ["Processing subarrays or substrings efficiently", "Sorting elements", "Searching graphs", "Allocating memory"], correctAnswer: "Processing subarrays or substrings efficiently", explanation: "A sliding window reuses work across adjacent windows to reduce complexity.", tags: ["arrays", "optimization"] },
  { question: "What is the time complexity of accessing an element by index in an array?", category: "DSA", topic: "Arrays", difficulty: "Beginner", type: "MCQ", options: ["O(1)", "O(n)", "O(log n)", "O(n^2)"], correctAnswer: "O(1)", explanation: "Arrays provide constant-time random access by index.", tags: ["arrays", "complexity"] },
];

const dbmsQuestions: SeedQuestion[] = [
  { question: "What is a primary key in a relational database?", category: "DBMS", topic: "Keys", difficulty: "Beginner", type: "MCQ", options: ["A unique identifier for each row", "A reference to another table", "An index on text columns", "A backup copy of data"], correctAnswer: "A unique identifier for each row", explanation: "A primary key uniquely identifies a record and cannot be null.", tags: ["keys", "database"] },
  { question: "What is a foreign key?", category: "DBMS", topic: "Keys", difficulty: "Beginner", type: "MCQ", options: ["A key that references another table's primary key", "A unique row identifier", "An encrypted key", "A default column value"], correctAnswer: "A key that references another table's primary key", explanation: "Foreign keys enforce referential integrity between tables.", tags: ["keys", "database"] },
  { question: "What does ACID stand for in database transactions?", category: "DBMS", topic: "Transactions", difficulty: "Intermediate", type: "MCQ", options: ["Atomicity, Consistency, Isolation, Durability", "Auto, Cache, Index, Data", "Add, Create, Insert, Delete", "Access, Control, Integrity, Data"], correctAnswer: "Atomicity, Consistency, Isolation, Durability", explanation: "ACID guarantees reliable processing of database transactions.", tags: ["transactions", "database"] },
  { question: "Which SQL clause filters groups after aggregation?", category: "DBMS", topic: "SQL", difficulty: "Intermediate", type: "MCQ", options: ["HAVING", "WHERE", "ORDER BY", "LIMIT"], correctAnswer: "HAVING", explanation: "HAVING filters grouped results; WHERE filters before grouping.", tags: ["sql", "clauses"] },
  { question: "Which normal form removes partial dependencies?", category: "DBMS", topic: "Normalization", difficulty: "Intermediate", type: "MCQ", options: ["2NF", "1NF", "3NF", "BCNF"], correctAnswer: "2NF", explanation: "2NF eliminates partial dependencies on a composite key.", tags: ["normalization", "schema"] },
  { question: "Which SQL command retrieves data from a table?", category: "DBMS", topic: "SQL", difficulty: "Beginner", type: "MCQ", options: ["SELECT", "INSERT", "UPDATE", "DELETE"], correctAnswer: "SELECT", explanation: "SELECT queries and returns rows from one or more tables.", tags: ["sql", "queries"] },
  { question: "What is a database index used for?", category: "DBMS", topic: "Indexes", difficulty: "Intermediate", type: "MCQ", options: ["Speeding up data retrieval", "Encrypting data", "Backing up tables", "Creating users"], correctAnswer: "Speeding up data retrieval", explanation: "Indexes improve read performance at the cost of slower writes.", tags: ["indexes", "performance"] },
  { question: "Which JOIN returns only rows with matching keys in both tables?", category: "DBMS", topic: "Joins", difficulty: "Intermediate", type: "MCQ", options: ["INNER JOIN", "LEFT JOIN", "RIGHT JOIN", "FULL OUTER JOIN"], correctAnswer: "INNER JOIN", explanation: "INNER JOIN keeps only matched rows from both tables.", tags: ["joins", "sql"] },
  { question: "What is a view in a database?", category: "DBMS", topic: "Views", difficulty: "Beginner", type: "MCQ", options: ["A virtual table based on a stored query", "A physical backup", "An index", "A trigger"], correctAnswer: "A virtual table based on a stored query", explanation: "Views present query results as if they were a table without storing data.", tags: ["views", "sql"] },
  { question: "What does a database transaction guarantee?", category: "DBMS", topic: "Transactions", difficulty: "Intermediate", type: "MCQ", options: ["All-or-nothing execution", "Faster query speed", "Data encryption", "User authentication"], correctAnswer: "All-or-nothing execution", explanation: "Transactions commit fully or roll back entirely to keep data consistent.", tags: ["transactions", "database"] },
  { question: "What is denormalization?", category: "DBMS", topic: "Optimization", difficulty: "Advanced", type: "MCQ", options: ["Adding redundancy to improve read performance", "Removing duplicate data", "Creating indexes", "Encrypting columns"], correctAnswer: "Adding redundancy to improve read performance", explanation: "Denormalization trades write complexity for faster reads via duplicated data.", tags: ["optimization", "performance"] },
  { question: "Which SQL clause is used to group rows before aggregation?", category: "DBMS", topic: "SQL", difficulty: "Beginner", type: "MCQ", options: ["GROUP BY", "ORDER BY", "HAVING", "WHERE"], correctAnswer: "GROUP BY", explanation: "GROUP BY collects rows sharing a property so aggregates can be applied.", tags: ["sql", "clauses"] },
];

const networkQuestions: SeedQuestion[] = [
  { question: "What does DNS (Domain Name System) do?", category: "Computer Networks", topic: "DNS", difficulty: "Beginner", type: "MCQ", options: ["Translates domain names to IP addresses", "Assigns IP addresses dynamically", "Encrypts web traffic", "Routes data packets"], correctAnswer: "Translates domain names to IP addresses", explanation: "DNS resolves human-friendly names like example.com to IP addresses.", tags: ["dns", "protocols"] },
  { question: "What is the default port for HTTPS?", category: "Computer Networks", topic: "Protocols", difficulty: "Beginner", type: "MCQ", options: ["443", "80", "21", "22"], correctAnswer: "443", explanation: "HTTPS uses port 443; HTTP uses port 80.", tags: ["protocols", "ports"] },
  { question: "Which protocol operates at the application layer of the OSI model?", category: "Computer Networks", topic: "OSI", difficulty: "Beginner", type: "MCQ", options: ["HTTP", "TCP", "IP", "Ethernet"], correctAnswer: "HTTP", explanation: "HTTP is an application-layer protocol; TCP/IP operate at lower layers.", tags: ["osi", "protocols"] },
  { question: "What is the key difference between TCP and UDP?", category: "Computer Networks", topic: "Protocols", difficulty: "Intermediate", type: "MCQ", options: ["TCP is connection-oriented and reliable; UDP is connectionless", "They are identical protocols", "UDP is reliable; TCP is not", "TCP is always faster than UDP"], correctAnswer: "TCP is connection-oriented and reliable; UDP is connectionless", explanation: "TCP guarantees delivery and ordering; UDP is lightweight and does not.", tags: ["protocols", "transport"] },
  { question: "Which addressing scheme uses 128-bit addresses?", category: "Computer Networks", topic: "IP", difficulty: "Beginner", type: "MCQ", options: ["IPv6", "IPv4", "MAC address", "Subnet mask"], correctAnswer: "IPv6", explanation: "IPv6 uses 128-bit addresses to overcome IPv4 exhaustion.", tags: ["addressing", "ip"] },
  { question: "What does ARP (Address Resolution Protocol) do?", category: "Computer Networks", topic: "Protocols", difficulty: "Intermediate", type: "MCQ", options: ["Maps IP addresses to MAC addresses", "Routes packets between networks", "Encrypts traffic", "Resolves domain names"], correctAnswer: "Maps IP addresses to MAC addresses", explanation: "ARP resolves a known IP address to its link-layer MAC address.", tags: ["protocols", "addressing"] },
  { question: "What is a MAC address?", category: "Computer Networks", topic: "Addressing", difficulty: "Beginner", type: "MCQ", options: ["A unique hardware identifier for a network interface", "An IP address assigned by DHCP", "A TCP port number", "An application-layer protocol"], correctAnswer: "A unique hardware identifier for a network interface", explanation: "MAC addresses are burned into NICs and used at the data link layer.", tags: ["addressing", "mac"] },
  { question: "What does HTTPS add on top of HTTP?", category: "Computer Networks", topic: "HTTP", difficulty: "Beginner", type: "MCQ", options: ["Encryption via TLS/SSL", "Faster transmission", "A different port only", "Compression"], correctAnswer: "Encryption via TLS/SSL", explanation: "HTTPS secures data in transit using TLS/SSL encryption.", tags: ["http", "security"] },
  { question: "What is a subnet mask used for?", category: "Computer Networks", topic: "Subnetting", difficulty: "Intermediate", type: "MCQ", options: ["Dividing an IP network into smaller subnets", "Encrypting data", "Assigning MAC addresses", "Resolving DNS"], correctAnswer: "Dividing an IP network into smaller subnets", explanation: "Subnet masks separate network and host portions of an IP address.", tags: ["subnetting", "addressing"] },
  { question: "Which HTTP method is considered idempotent?", category: "Computer Networks", topic: "HTTP", difficulty: "Intermediate", type: "MCQ", options: ["GET", "POST", "PATCH", "CONNECT"], correctAnswer: "GET", explanation: "GET returns the same result for repeated identical requests.", tags: ["http", "methods"] },
  { question: "What is a firewall?", category: "Computer Networks", topic: "Security", difficulty: "Beginner", type: "MCQ", options: ["A system that filters network traffic based on rules", "A type of router", "A DNS server", "An encryption algorithm"], correctAnswer: "A system that filters network traffic based on rules", explanation: "Firewalls permit or block traffic according to security policies.", tags: ["security", "network"] },
  { question: "How many layers does the OSI model define?", category: "Computer Networks", topic: "OSI", difficulty: "Beginner", type: "MCQ", options: ["7", "4", "5", "3"], correctAnswer: "7", explanation: "The OSI model has seven layers from physical to application.", tags: ["osi", "layers"] },
];

const osQuestions: SeedQuestion[] = [
  { question: "What is a process in an operating system?", category: "Operating Systems", topic: "Processes", difficulty: "Beginner", type: "MCQ", options: ["An instance of a running program", "A hardware component", "A file stored on disk", "A network packet"], correctAnswer: "An instance of a running program", explanation: "A process includes program code, current activity, and allocated resources.", tags: ["processes", "os"] },
  { question: "What is a thread?", category: "Operating Systems", topic: "Threads", difficulty: "Intermediate", type: "MCQ", options: ["A lightweight unit of execution within a process", "A hardware device", "A file format", "A network protocol"], correctAnswer: "A lightweight unit of execution within a process", explanation: "Threads share the process address space and enable concurrent execution.", tags: ["threads", "concurrency"] },
  { question: "What is a deadlock?", category: "Operating Systems", topic: "Deadlocks", difficulty: "Advanced", type: "MCQ", options: ["A circular wait where processes block each other for resources", "A process that finishes too quickly", "A memory leak", "A type of computer virus"], correctAnswer: "A circular wait where processes block each other for resources", explanation: "Deadlock occurs when processes hold resources while waiting for others held by each other.", tags: ["concurrency", "deadlocks"] },
  { question: "Which scheduling algorithm gives each process an equal time slice?", category: "Operating Systems", topic: "Scheduling", difficulty: "Intermediate", type: "MCQ", options: ["Round Robin", "First-Come First-Served", "Shortest Job First", "Priority Scheduling"], correctAnswer: "Round Robin", explanation: "Round Robin cycles processes with a fixed time quantum.", tags: ["scheduling", "cpu"] },
  { question: "What is virtual memory?", category: "Operating Systems", topic: "Memory", difficulty: "Beginner", type: "MCQ", options: ["Using disk space as an extension of RAM", "RAM only", "Cache memory", "Read-only memory"], correctAnswer: "Using disk space as an extension of RAM", explanation: "Virtual memory lets processes use more memory than physically available.", tags: ["memory", "os"] },
  { question: "What does paging do to memory?", category: "Operating Systems", topic: "Memory", difficulty: "Intermediate", type: "MCQ", options: ["Divides memory into fixed-size pages", "Encrypts memory contents", "Deletes unused memory", "Compresses files on disk"], correctAnswer: "Divides memory into fixed-size pages", explanation: "Paging maps fixed-size pages to frames for efficient allocation.", tags: ["memory", "paging"] },
  { question: "What is a mutex?", category: "Operating Systems", topic: "Synchronization", difficulty: "Intermediate", type: "MCQ", options: ["A lock ensuring mutual exclusion to a shared resource", "A type of process", "A file system", "A network device"], correctAnswer: "A lock ensuring mutual exclusion to a shared resource", explanation: "A mutex lets only one thread access a critical section at a time.", tags: ["sync", "concurrency"] },
  { question: "What is a race condition?", category: "Operating Systems", topic: "Concurrency", difficulty: "Intermediate", type: "MCQ", options: ["An outcome that depends on unpredictable timing of concurrent access", "A very fast CPU", "A type of deadlock", "A memory allocation error"], correctAnswer: "An outcome that depends on unpredictable timing of concurrent access", explanation: "Race conditions happen when unsynchronized threads modify shared data.", tags: ["concurrency", "sync"] },
  { question: "What is a semaphore?", category: "Operating Systems", topic: "Synchronization", difficulty: "Advanced", type: "MCQ", options: ["A synchronization primitive for controlling resource access", "A process scheduler", "A file format", "A network device"], correctAnswer: "A synchronization primitive for controlling resource access", explanation: "Semaphores use counters to coordinate access among multiple threads.", tags: ["sync", "concurrency"] },
  { question: "What is a context switch?", category: "Operating Systems", topic: "Scheduling", difficulty: "Intermediate", type: "MCQ", options: ["Saving and restoring process state to switch CPUs", "Deleting a process", "Compiling source code", "A type of deadlock"], correctAnswer: "Saving and restoring process state to switch CPUs", explanation: "Context switching enables multitasking by swapping process state.", tags: ["scheduling", "cpu"] },
  { question: "What is a system call?", category: "Operating Systems", topic: "Interface", difficulty: "Intermediate", type: "MCQ", options: ["A request by a program to the OS kernel", "A network packet", "A hardware interrupt only", "A type of computer virus"], correctAnswer: "A request by a program to the OS kernel", explanation: "System calls provide the interface between user programs and the kernel.", tags: ["interface", "kernel"] },
  { question: "What does a file system manage?", category: "Operating Systems", topic: "File System", difficulty: "Beginner", type: "MCQ", options: ["Storage and organization of files", "CPU scheduling", "Network traffic", "Only memory allocation"], correctAnswer: "Storage and organization of files", explanation: "File systems store, name, and retrieve data on storage devices.", tags: ["storage", "file-system"] },
];

const hrQuestions: SeedQuestion[] = [
  { question: "How should you answer 'Tell me about yourself'?", category: "HR", topic: "Introduction", difficulty: "Beginner", type: "MCQ", options: ["Give a concise professional overview", "Recite your full resume word for word", "List only your hobbies", "Stay silent"], correctAnswer: "Give a concise professional overview", explanation: "Structure a short summary around background, skills, and motivation.", tags: ["communication", "introduction"] },
  { question: "How should you discuss your weaknesses in an interview?", category: "HR", topic: "Weaknesses", difficulty: "Intermediate", type: "MCQ", options: ["Share an honest weakness with an improvement plan", "Claim you have no weaknesses", "Blame a former colleague", "List fake strengths"], correctAnswer: "Share an honest weakness with an improvement plan", explanation: "Showing self-awareness and growth is what interviewers look for.", tags: ["self-awareness", "growth"] },
  { question: "Where do you see yourself in 5 years?", category: "HR", topic: "Goals", difficulty: "Intermediate", type: "MCQ", options: ["Growth aligned with the company's trajectory", "Retired and uninterested", "Exactly unchanged", "Unsure and dismissive"], correctAnswer: "Growth aligned with the company's trajectory", explanation: "Show ambition that fits the role and the organization's path.", tags: ["goals", "motivation"] },
  { question: "How do you handle conflict with a coworker?", category: "HR", topic: "Conflict", difficulty: "Intermediate", type: "MCQ", options: ["Through respectful dialogue to find common ground", "By avoiding them entirely", "By escalating immediately to management", "By quitting the project"], correctAnswer: "Through respectful dialogue to find common ground", explanation: "Mature communication and collaboration resolve conflicts constructively.", tags: ["communication", "teamwork"] },
  { question: "Why should we hire you?", category: "HR", topic: "Value", difficulty: "Intermediate", type: "MCQ", options: ["Your skills and attitude match the role's needs", "Because you simply need a job", "Because you are the only applicant", "Because you asked politely"], correctAnswer: "Your skills and attitude match the role's needs", explanation: "Connect your strengths and experience to the employer's goals.", tags: ["positioning", "value"] },
  { question: "How do you prioritize your work?", category: "HR", topic: "Time Management", difficulty: "Intermediate", type: "MCQ", options: ["By urgency and impact", "Always by the easiest task first", "Randomly as they arrive", "By delegating everything to others"], correctAnswer: "By urgency and impact", explanation: "Frameworks like the Eisenhower matrix help prioritize effectively.", tags: ["time-management", "productivity"] },
  { question: "How do you handle tight deadlines?", category: "HR", topic: "Time Management", difficulty: "Intermediate", type: "MCQ", options: ["Break work into parts and communicate early", "Panic and do nothing", "Ignore the deadline", "Quit immediately"], correctAnswer: "Break work into parts and communicate early", explanation: "Planning and proactive communication keep deadlines achievable.", tags: ["time-management", "pressure"] },
  { question: "How do you respond to constructive criticism?", category: "HR", topic: "Feedback", difficulty: "Intermediate", type: "MCQ", options: ["Receive it openly and use it to improve", "Ignore it completely", "Argue immediately", "Take it personally and withdraw"], correctAnswer: "Receive it openly and use it to improve", explanation: "A growth mindset turns feedback into measurable improvement.", tags: ["feedback", "growth"] },
  { question: "Describe a time you failed. How should you answer?", category: "HR", topic: "Failure", difficulty: "Intermediate", type: "MCQ", options: ["Share honestly and explain lessons learned", "Lie and say you never fail", "Blame others for the failure", "Refuse to answer"], correctAnswer: "Share honestly and explain lessons learned", explanation: "Honest reflection with lessons shows resilience and maturity.", tags: ["growth", "self-awareness"] },
  { question: "What motivates you at work?", category: "HR", topic: "Motivation", difficulty: "Beginner", type: "MCQ", options: ["Solving meaningful problems and growing", "Money only, nothing else", "Nothing in particular", "Office gossip"], correctAnswer: "Solving meaningful problems and growing", explanation: "Connecting personal drivers to the role demonstrates fit and drive.", tags: ["motivation", "engagement"] },
  { question: "How do you work in a team?", category: "HR", topic: "Teamwork", difficulty: "Beginner", type: "MCQ", options: ["Collaborate, communicate, and support teammates", "Work alone and avoid contact", "Compete aggressively with peers", "Delegate all work upward"], correctAnswer: "Collaborate, communicate, and support teammates", explanation: "Empathy and shared goals are core to effective teamwork.", tags: ["teamwork", "communication"] },
  { question: "What are your salary expectations?", category: "HR", topic: "Compensation", difficulty: "Intermediate", type: "MCQ", options: ["A researched range aligned with the role", "An arbitrary very large number", "Refuse to ever discuss it", "The absolute minimum only"], correctAnswer: "A researched range aligned with the role", explanation: "Market-based ranges show preparation and realism.", tags: ["compensation", "preparation"] },
  { question: "Do you have any questions for us?", category: "HR", topic: "Questions", difficulty: "Beginner", type: "MCQ", options: ["Ask thoughtful questions about the role and team", "Say no immediately", "Ask only about salary", "End the interview abruptly"], correctAnswer: "Ask thoughtful questions about the role and team", explanation: "Good questions show genuine interest and engagement.", tags: ["engagement", "curiosity"] },
];

const allQuestions: SeedQuestion[] = [
  ...jsQuestions,
  ...reactQuestions,
  ...tsQuestions,
  ...htmlQuestions,
  ...cssQuestions,
  ...dsaQuestions,
  ...dbmsQuestions,
  ...networkQuestions,
  ...osQuestions,
  ...hrQuestions,
].map((q) => ({ ...q, options: shuffleArray(q.options) }));

const achievements = [
  { title: "First Quiz", description: "Complete your first quiz", icon: "🎯", requirement: { type: "quizzes_completed", value: 1 } },
  { title: "Quiz Enthusiast", description: "Complete 10 quizzes", icon: "📝", requirement: { type: "quizzes_completed", value: 10 } },
  { title: "Question Solver", description: "Solve 50 questions", icon: "✅", requirement: { type: "questions_solved", value: 50 } },
  { title: "Knowledge Master", description: "Solve 100 questions", icon: "🏆", requirement: { type: "questions_solved", value: 100 } },
  { title: "Week Warrior", description: "Maintain a 7-day streak", icon: "🔥", requirement: { type: "streak_days", value: 7 } },
  { title: "Sharpshooter", description: "Achieve 90% accuracy", icon: "🎯", requirement: { type: "accuracy_percentage", value: 90 } },
  { title: "First Interview", description: "Complete your first mock interview", icon: "🎤", requirement: { type: "interviews_completed", value: 1 } },
];

const seedDatabase = async (): Promise<void> => {
  try {
    await connectDB();

    await Question.deleteMany({});
    await Question.insertMany(allQuestions);
    console.log(`Seeded ${allQuestions.length} questions`);

    await Achievement.deleteMany({});
    await Achievement.insertMany(achievements);
    console.log(`Seeded ${achievements.length} achievements`);

    await mongoose.disconnect();
    console.log("Database seeded successfully");
    process.exit(0);
  } catch (error) {
    console.error("Seeding error:", error);
    process.exit(1);
  }
};

void seedDatabase();
